import type { Bookmark } from "../types.js";

export function exportJson(bookmarks: Bookmark[]): string {
  return JSON.stringify(bookmarks, null, 2);
}

export function exportMarkdown(bookmarks: Bookmark[]): string {
  const byCat = groupByCategory(bookmarks);
  const lines = ["# SyncMark export", ""];
  for (const [category, items] of byCat) {
    lines.push(`## ${category}`, "");
    for (const b of items) {
      const tags = b.tags.length ? ` (${b.tags.join(", ")})` : "";
      lines.push(`- [${b.title}](${b.url})${tags}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function exportHtml(bookmarks: Bookmark[]): string {
  const byCat = groupByCategory(bookmarks);
  const parts = [
    "<!DOCTYPE NETSCAPE-Bookmark-file-1>",
    "<!-- Generated by SyncMark -->",
    "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">",
    "<TITLE>Bookmarks</TITLE>",
    "<H1>Bookmarks</H1>",
    "<DL><p>",
  ];
  for (const [category, items] of byCat) {
    parts.push(`    <DT><H3>${escapeHtml(category)}</H3>`, "    <DL><p>");
    for (const b of items) {
      const add = Math.floor(new Date(b.createdAt).getTime() / 1000);
      parts.push(
        `        <DT><A HREF="${escapeAttr(b.url)}" ADD_DATE="${add}">${escapeHtml(b.title)}</A>`,
      );
    }
    parts.push("    </DL><p>");
  }
  parts.push("</DL><p>");
  return parts.join("\n");
}

function groupByCategory(bookmarks: Bookmark[]): Array<[string, Bookmark[]]> {
  const map = new Map<string, Bookmark[]>();
  for (const b of bookmarks) {
    const key = b.category || "General";
    const list = map.get(key) ?? [];
    list.push(b);
    map.set(key, list);
  }
  return [...map.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function escapeAttr(s: string): string {
  return escapeHtml(s).replace(/"/g, "&quot;");
}
